version: 0.2

phases:
  pre_build:
    commands:
      - echo Setting up kubeconfig
      - aws eks update-kubeconfig --region us-east-1 --name bhargav-cluster
  build:
    commands:
      - echo Applying K8s manifests
      - kubectl apply -f k8s/
