apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: 423623849965.dkr.ecr.us-east-1.amazonaws.com/backend-ecommerce:latest
        ports:
        - containerPort: 8000
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: backend.settings
        envFrom:
        - secretRef:
            name: mysql-secret
